[package]
name = "lycan"
version = "0.1.0"
authors = ["Aydar <lesterrry@rambler.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
directories = "2.0.2"
rand = "0.6.5"